### ISSUE TITLE
Declaration, Parsing, Implementation and Execution of Operator Pipeline (v1)

### ISSUE THREAD

**Issue by ppanopticon** [vitrivr/vitrivr-engine#1]
# Task description

We require the means to declare, parse, implement and execute an arbitrary data ingest pipeline in vitrivr-engine.

- [ ] **Declaration:** An data ingest pipeline for data indexing and ingesting can be configured declaratively using a format such as JSON or TOML. The format should be be capable of capturing all the degrees of freedom possible in such a pipeline (even though the simple case is going to be rather linear).
- [ ] **Parsing:** A so described data ingest  pipeline must be parsed by **vitrivr-engine**, so that it can be represented as a series of nexted Kotlin classes. Use Kotlin's serialization framework for this, if possible!
- [ ] **Implementation:** The parsed data ingest pipeline must be implemented into a sequence of ``Operator`` implementations (i.e., ``Enumerator``, ``Decoder``, ``Extractor``,  ``Segmenter`` and ``Transformer``)!
- [ ] **Execution:** The resulting operator pipeline must then be executed using the ``ExecutionServer.execute()`` method!
- [ ] A running implementation should be integrated as a CLI command (``<schema> extract <path-to-file>``).

## Dependencies

- The schema management (``SchemaManager``)
- Execution pipeline (``ExecutionServer``) 

## Boundary conditions

- Use Kotlin's serialization framework for this, if possible (see ``org.vitrivr.engine.core.config.VitrivrConfig`` for example)!
- Instances of ``Enumerator``, ``Decoder``,  ``Segmenter`` and ``Transformer``  are declared by name and must be obtained using Java's ``ServiceLoader`` mechanism. This may require some sort of provider class!
- - Instances of ``Extractor`` can be declared by name (explicitly) or field in the schema (implicitly). Facilites to access them, already exist !
- Instances of ``Enumerator``, ``Decoder``,  ``Segmenter`` and ``Transformer``  can potentially be parameterised arbitrarily (e.g., through a map)!
