### ISSUE TITLE
Persistent Operator Pipeline and RESTful API (v1) 

### ISSUE THREAD

**Issue by ppanopticon** [vitrivr/vitrivr-engine#10]
# Task Description
Now that an extraction pipeline can be defined and setup, it should be possible to register persistent pipelines as some sort of template. Such pipelines should:

- [x] Be registered for a specific schema and named using a unique name (per schema). Registration can take place via CLI  using the default format.
- [x] Allow the extraction of files and groups of files via CLI using the name of the template (instead of pointing to the configuration file).
- [x] Allow the extraction of files via RESTful API using the name of the template. This requires an additional RESTful endpoint, that allows for the submission of single files.

## Dependencies
Requires resolutions of #1 and #11

## Boundary Conditions
Take into account requirements described in #9
