### ISSUE TITLE
Bootstrap RESTful API and CLI

### ISSUE THREAD

**Issue by ppanopticon** [vitrivr/vitrivr-engine#11]
# Task Description
The use of RESTful API and CLI should be bootstrapped:

- [x] The RESTful API should be structured around schemas (i.e., a call could look like this `<schema> <command>`
- [x] The CLI API should be structured around schemas (i.e., a call could look like this `<schema> <command>`
- [x] Obviously, there are also global (i.e., schema independent commands).

## Dependencies
None

## Boundary Conditions
RESTful API should use Open API if possible.
