### ISSUE TITLE
Context for Operator Pipelines (Extraction / Retrieval)

### ISSUE THREAD

**Issue by ppanopticon** [vitrivr/vitrivr-engine#12]
# Task Description
Now that a first version of our Extraction Operator Pipeline is seems to be working, I have spotted a minor things that should be adjusted. 

The reason the adjustment is needed can best be illustrated using the `ContentFactory`. Instances of this class are handed to the operators that need it using the parameter map. Depending on how this is implemented, every operatore uses its own instance, which defeats the purpose of the factory when, e.g., considering caching.

Instead, I would suggest this to be setting that is global for an instance of a extraction pipeline. Furthermore, I would propose a `Context` object, that can hold helper classes such as the `ContentFactory`. This `Context` is then handed to all the the operators, which then can decide whether or not to use certain classes.

The issue involves the following changes:

- [x] Create a `Context` class, that can hold instances of helper classes that are needed for an extraction pipeline.
- [x] Hand `Context` object to all Operators upon instantiation of a pipeline.
- [x] Allow `Context` class to be configurable using the extraction configuration.

## Dependencies
None

## Boundary Conditions
None
