### ISSUE TITLE
Technical Metadata Extraction for Visual and Temporal Retrievables

### ISSUE THREAD

**Issue by ppanopticon** [vitrivr/vitrivr-engine#13]
# Task Description
For 2D visual and temporal retrievables (e.g., images, video and audio frames), we need mechanisms to extract, store and retrieve technical metadata per retrievable.

- [x] Fundamentally, metadata of a certain type (e.g., temporal) should be implemented as a descriptor of type `struct`
- [x] Implement and integrate temporal metadata extraction and retrieval for video and audio (milliseconds, frame number)
- [x] Implement and integrate spatial metadata extraction and retrieval for video and images (width, height)

## Dependencies
None

## Boundary Conditions
None

**Comment by ppanopticon** [comment]
This has been done with `TemporalMetadata`, `FileSourceMetadata` and `VideoSourceMetadata`. If additional features are needed, open new ticket.
