### ISSUE TITLE
External Analyser / Feature: Boilerplate Implementation

### ISSUE THREAD

**Issue by ppanopticon** [vitrivr/vitrivr-engine#2]
# Task Description
Certain features rely on external services (e.g., a neural network in Python). vitrivr-engine should offer facilities, to access such features using a web-service architecture.

- [x] **Interface Definition:** For communication, the external service and vitrivr-engine should communicate using a well-defined RESTful interface via HTTP / HTTPS. Generally, vitrivr-engine sends some type of ``Content`` to the service and retrieves some sort of ``Descriptor``(s).
- [x] **Abstract Implementation:** To speed-up development, vitrivr-engine should sport abstract ``ExternalAnalyser``, ``ExternalRetriever`` and ``ExternalExtractor`` implementations, that can be parameterised to invoke a specific, external service adhering to aforementioned interface definitions. Potential parameters could be ``host``, ``port``, ``feature`` etc.
- [x] **Reference Implementations:** The mechanism should be implemented as two concrete features for CLIP and DINOv2.

The external service(s) can and should be hosted in a dedicated repository. Optionally, one could make this service configurable and extensible in terms of what concrete features it hosts (i.e., build a feature server).

## Dependencies

- `Extractor`, `Retriever` and `Analyser` implementations
- ``Schema`` and ``SchemaManager``

## Boundary conditions
- Communication should be standardised using Open API (if possible)
- Named parameters can be provided with the schema definition (see ``Schema`` and ``SchemaManager``)
