### ISSUE TITLE
Cottontail DB Database Connection (v1)

### ISSUE THREAD

**Issue by ppanopticon** [vitrivr/vitrivr-engine#3]
# Task Description

We need a working ``Connection`` and ``ConnectionProvider`` for Cottontail DB. The implementations should support the following:

- [x] A `Reader`, `Writer` and `Initializer` for `Retrievable`s
- [x] A `Reader`, `Writer` and `Initializer` for `VectorDescriptor`s
- [x] A `Reader`, `Writer` and `Initializer` for all `ScalarDescriptor`s
- [x] A `Reader`, `Writer` and `Initializer` for `LabelDescriptor`

## Dependencies
None

## Boundary Conditions
None
