### ISSUE TITLE
Review Content Derivation Mechanism

### ISSUE THREAD

**Issue by ppanopticon** [vitrivr/vitrivr-engine#4]
# Task Description

In its current form, the mechanism for content derivation is not ideal and should be adjusted as follows:

- [ ] Fundamentally, content can be derived using the `RetrievableWithContent.deriveContent()` method. This should always execute the derivation process eagerly.
- [ ] A so `DerivedContent` may (or may not) be added to the list of `Content` elements a `RetrievableWithContent` holds (provided that `RetrievableWithContent.Mutable` is implemented). I would argue, that this is probably use-case dependent.
- [ ] The question of whether (or not) derived content implementation is cached or held in memory, should be delegated to the `ContentProvider` mechanism described in issue ...

## Dependencies
- `Content`

## Boundary Conditions

- Generally, I would use the same caching facilities for original and derived content (in case, caching is requested).
