### ISSUE TITLE
Simple Boolean Retrieval

### ISSUE THREAD

**Issue by rahelarnold98** [vitrivr/vitrivr-engine#40]
# Task Description
Cineast sported Boolean Retrieval with simple comparisons, as well as ranges (and for tags, which are ignored in this task). Therefore, this should - as generalised as possible - be introduced to vitrivr-engine.

 The Boolean retrieval should support:

- [x] Comparison of literal values to (sub-fields) using common comparison operations (=, !=, >, <, >=, <=)
- [x] Support for different data types (numbers, strings, dates)
- [ ] **Optional:** Complex queries containing (`AND`, `OR` and `NOT`)

In practice, there are two major uses in a query pipeline, which probably need to be addressed differently:

- [x] Using Boolean queries as a data source in a `Retriever`
- [ ] **Optional:**  Using Boolean queries to restrict a result set based on a boundary condition.

## Dependencies
- None

## Boundary Conditions
- Should work on sub-fields in a struct field.
- May require major changes to query definition language

**Comment by ppanopticon** [comment]
**Bump:** Update description to capture Goal. Please feel free to add things to the list or clarify.

**Comment by sauterl** [comment]
Update: A first iteration of boolean retrieval for sub-fields is open as a PR in #50

**Comment by ppanopticon** [comment]
Closing issue. Moving optional requirements to separate ticket.
