### ISSUE TITLE
Revisit Persistence

### ISSUE THREAD

**Issue by ppanopticon** [vitrivr/vitrivr-engine#52]
# Task Description

Currently, every `Operator` is an extraction pipeline is responsible for persisting its part of the information independently of all the others. This approach, while simple, has several shortcomings. Firstly, it makes optimisation and consolidation of queries to the database very difficult. Secondly, error handling and reconciliation is almost impossible.

Therefore, this issue proposes to make the following adjustments to how data is being persisted:

- [ ] Henceforth, `Operator`s add to an in-memory graph-structure of the incoming `Retrievable`, e.g., by appending `Descriptor`s or `Relationships`
- [ ] Persistence is facilitated by a final `DataSink` operator that orchestrates the write of changes to the database.
- [ ] Every entity in that graph (i.e., `Retrievable`, `Descriptor` or `Relationships`) can be marked as `transient`, for it to be ignored when writing data to the database.
- [ ] **Optional:** Ideally, and if supported by the database layer, writes should be transactional.

## Dependencies
- #51 

## Boundary Conditions
- None
