### ISSUE TITLE
Data Migration from Cineast to vitrivr-engine

### ISSUE THREAD

**Issue by ppanopticon** [vitrivr/vitrivr-engine#6]
# Task Description

For V3C, we need a mechanism that allows  for the migration of the data stored in Cineast to the new vitrivr-engine, so as to prevent re-extraction of the entire collection.

- [x] Migration script to transfer media objects and media segments to `Retrievable`s
- [x] Migration script to transfer metadata into dedicated fields  (with `Descriptors`)
- [x] Migration script to transfer relevant features as fields (with `Descriptors`)

## Dependencies
- Issue #3, so that the mapping from conceptual object to entity is stable.

## Boundary Conditions
- This is more of a mid-term goal and not necessarily part of the first prototype milestone.
- Scripts must not necessarily be a part of the vitrivr-engine project

**Comment by ppanopticon** [comment]
Since this functionality has been around for some time now, I close this issue.
