### ISSUE TITLE
Basic Operations for new Pipeline Design

### ISSUE THREAD

**Issue by ppanopticon** [vitrivr/vitrivr-engine#67]
# Task Description

The new operator pipeline design for both extraction as well as retrieval allows for many ways to combine streams of retrievable. In this issue, we should have a high-lvl discussion what basic operations should be allowed on these stream. This involves:

- [x] Different ways of merging multiple streams into a single stream
- [x] Different ways to manipulate filter individual elements
- [x] Other manipulations I may have forgotten

Currently, we only support filtering by `Retrievable` type. For merging, we support the following primitives:

**Merge:** Simply emits every incoming `Retrievable` on every input and merges them into a single stream. Ordering of `Retrievable` may be random.
**Combine:** Waits of an identical `Retrievable` on each input, before it emits one instance of that `Retrievable` at the output.
**Concat:** Collects and emits inputs in order (first input 1, then input 2 etc.)

Other semantics may be possible (e.g., Zip by introducing a transient Zipping-Retrievable that holds a relationship to each element in the Zip operation). The idea of this ticket is to brainstorm common cases and implement them.

## Dependencies
None

## Boundary Conditions
None
