### ISSUE TITLE
Revisit Retrieval Pipeline

### ISSUE THREAD

**Issue by ppanopticon** [vitrivr/vitrivr-engine#68]
# Task Description

In light of the changes introduced in #51, the design of the retrieval pipeline needs slight adjustment. I did not address this in #51 since I'm not too familiar with how the different operators work and what input they expect.

Roughly, I'd propose the following changes:

- [ ] The interfaces `org.vitrivr.engine.core.operators.retrieve.Aggregator` and `org.vitrivr.engine.core.operators.retrieve.Transformer` can be replaced by the `org.vitrivr.engine.core.operators.general.Transformer` interface.
- [ ] `org.vitrivr.engine.core.operators.general.TransformerFactory` probably needs some adjustment, to support both retrieval and extraction. Easiest way would be to make the method `newTransformer` accept `Context` as parameter instead of `IndexContext`.
- [ ] Existing retrieval operators need to be adjusted. Special attention should be paid to operators that require a specific ordering of incoming elements (e.g., for temporal scoring).

## Dependencies
- May depends on primitives added in #67

## Boundary Conditions
None

**Comment by ppanopticon** [comment]
I assigned this to you @lucaro since you added the existing retrieval operations.

**Comment by lucaro** [comment]
I'll have a look

**Comment by lucaro** [comment]
Added relevant changes in https://github.com/vitrivr/vitrivr-engine/tree/feature/68. @ppanopticon please have a look to see if that is along the lines of what you had in mind.

**Comment by lucaro** [comment]
@ppanopticon any comments?

**Comment by ppanopticon** [comment]
Looks good to me. If it works we can merge it. I opened PR #71 .
