### ISSUE TITLE
Preview and Thumbnails for ImageContent

### ISSUE THREAD

**Issue by ppanopticon** [vitrivr/vitrivr-engine#7]
# Task Description
In order to display a preview of a ``Retrievable``, we must be able to generate a thumbnail or preview images. There is going to be a dedicated `Analyser` and `Extractor` for that (no `Retriever`):

- [ ] Build `Analyser` and `Extractor` needed to generate previews / thumbnails from image content.
- [ ] Store image content in a to be defined location (global configuration). Probably, previews should be physically separated per schema.
- [ ] Create API endpoint in `vitrivr-query` hat allows for access to preview using a `Retrievable`'s UUID. The schema of the lookup could be as follows: `api/<schema>/previews/<uuid>`

## Dependencies
None

## Boundary Conditions
- Output format should be configurable (PNG and JPEG)
- Output resolution should be configurable (parameters)
