### ISSUE TITLE
Factories for Content-Elements

### ISSUE THREAD

**Issue by ppanopticon** [vitrivr/vitrivr-engine#8]
# Task Description
Implementations of the `Content` (and sub-interfaces, such as, `ImageContent`) can come in different flavours, e.g., content held in memory vs. content backed by a file on disk. 

We require these flavours for very practical reasons, since the sheer volume of ``Content`` generated during an extraction may simply lead to an out-of-memory situation. Having different implementations allows us to tailor an instance based on the use-case and the setup.

In order to be able to generate these `Content` elements for a particular setup, vitrivr-engine should rely on a factory pattern:

- [x] **Interface:** The new `ContentFactory` interface defines the signature of such a factory. It must be able to generate the `Content` based on a `MediaType` and some actual content (e.g., a `BufferedImage` for image). Since a `ContentFactory` may chose to only support specific `MediaType`s, this should be advertised as well. Furthermore, one could characterise the `ContentFactory` w.r.t. to how they use memory.
- [x] **Usage:** All classes that potentially generate `Content` (e.g., `Decoder`, `Segmenter`, `Extractor`, `Transformer`) receive a particular `ContentFactory` instance upon creation. Instead of creating `Content` classes directly, the use the `ContentFactory` to do so.
- [x] **In-memory Implementation:** The new `InMemoryContentFactory` implementation generates pure in-memory `Content` elements (e.g., `InMemoryImageContent`).
- [x] **Cached Implementation:** The new `CachedContentFactory` implementation generates `Content` elements that are backed by an on-disk cache (e.g., `InMemoryImageContent`). That is, if memory pressure becomes too high, the in-memory representation is freed-up and the original content can be loaded from disk again upon request. This happens transparently.

## Dependencies
- `Content`

## Boundary Conditions
- The aforementioned implementations act as fallback facilities during indexing, in case a specific `ContentFactory` implementation does not support a specific `MediaType`. Hence, it must be able to generate `Content` for all 'MediaTypes` supported by vitrivr-engine.
- One can work with a caching library such as Caffeine or with `SoftReferences`.
