### ISSUE TITLE
[XRECO] Extraction via RESTful API

### ISSUE THREAD

**Issue by ppanopticon** [vitrivr/vitrivr-engine#9]
# Task Description
For the XRECO project, it must be possible the extract individual assets (e.g., images, videos, 3D models) via a RESTful API call.
Hence, we need 

- [ ] An API endpoint for starting an extraction asynchronously for a file (file upload)
- [ ] The API endpoint should return directly, returning a retrievable ID for the extracted asset
- [ ] An API endpoint that allows us to query the status of an extraction

## Dependencies
None

## Boundary Conditions
See the [sequence diagram](https://scm.atosresearch.eu/ari/xreco/wp3/common/sequencediagrams/-/blob/main/content_ingest.txt).
